# Generated by Django 4.1.2 on 2022-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField(max_length=200)),
                ('output', models.TextField(max_length=50)),
            ],
        ),
    ]
