# Generated by Django 4.1.2 on 2022-10-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.TextField(max_length=10000000000),
        ),
    ]
