# Generated by Django 4.1.2 on 2022-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.TextField(max_length=100),
        ),
    ]
