# Generated by Django 4.1.2 on 2022-10-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
