# Generated by Django 4.1.2 on 2022-10-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_code_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='output',
            field=models.TextField(max_length=1000),
        ),
    ]
