# Generated by Django 4.1.2 on 2022-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_output'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='output',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
