# Generated by Django 4.1.2 on 2022-10-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_commments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commments',
            new_name='comments',
        ),
    ]
