# Generated by Django 4.1.2 on 2022-10-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_commments_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='active',
        ),
    ]
