# Generated by Django 4.1.2 on 2022-10-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_comments_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='Post',
            new_name='post',
        ),
    ]
