# Generated by Django 4.1.2 on 2022-10-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comments_options_rename_post_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
